#配置该服务的端口
server:
  port: 8000
files:
  ip: localhost   #本机Ip,主要用于存储文件（存在本地服务器），若是需要使用第三方存储服务请按需修改
  port: 8000   #存储文件的服务器的端口
  upload:
    path: D:/oldData/JavaProject/XIN-Mix/xmix-manager/src/main/resources/static/
#Nacos的相关配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   #配上自己的nacos服务地址，注意和自己的cloud版本对应
  application:
    name: xmix-manager  # 服务的名字

  # 数据库的设置
  datasource:
    url: jdbc:mysql://192.168.133.132:3306/xmix_manager  #设置数据库的连接
    #注意需要引入mysql的驱动依赖
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #设置mapper映射文件的位置

#线程池的配置
xmix:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

