#配置服务的端口
server:
  port: 9000
#配置本地存储的路径
files:
  store:
    path: D:/oldData/JavaProject/XIN-Mix/xmix-manager/src/main/resources/static/
#Nacos的相关配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: xmix-blog
  #引入mybatis之后需要对数据库进行配置
  datasource:
    url: jdbc:mysql://192.168.133.132:3306/xmix_manager  #此处需要改成该服务操作的数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #设置mapper映射文件的位置
